# -*- coding: utf-8 -*-
"""Assignment_1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1BomtFrIsU53dOlwXpFo1rjLQcb9i1Ulk
"""

import pandas as pd

#Read the provided CSV file ‘data.csv’.
df = pd.read_csv('data.csv')
df

#Show the basic statistical description about the data.

df.describe()

#Check if the data has null values.

df.isnull().any()

#Replace the null values with the mean

mean=df['Calories'].mean()
df['Calories'].fillna(value=mean, inplace=True)

#replacing Null values with particular columns mean value

df.isnull().any()
#check any column has null values after replacing

#Select at least two columns and aggregate the data using: min, max, count, mean.

df.agg({'Duration' : ['min', 'max', 'count', 'mean'], 'Maxpulse' : ['min', 'max', 'count', 'mean'],
        'Calories' : ['min', 'max', 'count', 'mean'] })
#agg method to aggreate operation on the dataframe

#Filter the dataframe to select the rows with calories values between 500 and 1000.
#& operator to filter the dataframe

df[(df['Calories'] >= 500) & (df['Calories'] <= 1000)]

#Filter the dataframe to select the rows with calories values > 500 and pulse < 100.

df[(df['Calories'] > 500) & (df['Pulse'] < 100)]

#Create a new “df_modified” dataframe that contains all the columns from df except for “Maxpulse”.

df_modified = df[['Duration', 'Pulse', 'Calories']].copy()
#copy method to create an another data frome with specified columns from the original dataframe.
df_modified

# Delete the “Maxpulse” column from the main df dataframe

df.pop('Maxpulse')
 #pop method to remove a column from the data frame
df

#Convert the datatype of Calories column to int datatype.

df['Calories'] = df['Calories'].astype(int)
#astype function converts one data type into another
df.dtypes